const en = {
  brand: 'Ulfa',
  loading: 'Opening…',
  invalidLink: 'This link doesn’t open any gift.',
  inactive: 'The store has paused this gift.',
  networkError: 'No connection. Check your internet and try again.',
  retry: 'Try again',
  back: 'Back',
  next: 'Next',
  continue: 'Continue',
  close: 'Close',
  done: 'Done',
  remove: 'Remove',
  uiLanguage: 'العربية',
  steps: ['The lock', 'What’s inside', 'Filling it', 'A last look'],
  stepOf: (n: number, total: number) => `Step ${n} of ${total}`,

  welcomeEyebrow: 'Before it reaches them',
  welcomeTitle: 'A gift only they can open',
  welcomeBody: 'Lock it with something only the two of you know, fill it with your words, photos and voice — then see it exactly as they will.',
  welcomePrivacy: 'Everything is locked on this phone before it leaves. Nobody else can open it — not even us.',
  giftLanguage: 'The gift will speak',
  start: 'Begin',

  lockEyebrow: 'The lock',
  lockTitle: 'What will open it?',
  lockBody: 'They’ll be asked this when they tap the necklace. Pick something they’ll know without thinking.',
  changeLockTitle: 'A new lock',
  types: { PIN: 'A number', DATE: 'A date', TEXT: 'A question' },
  typeHints: {
    PIN: '6 digits only you two know.',
    DATE: 'The day you met, an anniversary…',
    TEXT: 'They answer in their own words.',
  },
  hint: 'A little hint for them',
  optional: 'optional',
  hintPlaceholder: 'The day we first met',
  question: 'Your question',
  questionPlaceholder: 'Where was our first trip?',
  answer: 'The answer',
  answerAgain: 'Once more, to be sure',
  pin: 'Six digits',
  pinAgain: 'The same six again',
  date: 'The date',
  mismatch: 'Those two don’t match.',
  problems: {
    required: 'This one’s needed.',
    pinLength: 'It needs exactly six digits.',
    pinWeak: 'Too easy to guess — avoid 123456 or repeated digits.',
    dateInvalid: 'That date doesn’t exist.',
    textShort: 'A slightly longer answer, please.',
  },
  answerNote: 'Capitals, hamza and diacritics won’t matter.',
  lockScreenTitle: 'For your eyes only',
  theySee: 'What they’ll see',

  keepEyebrow: 'One thing to keep',
  keepTitle: 'Your spare key',
  keepBody: 'If the answer ever slips your mind, this code is the only way back in. We can’t reset it for you.',
  copy: 'Copy',
  copied: 'Copied',
  download: 'Save as file',
  screenshotTip: 'A screenshot works too.',
  keepConfirm: 'I’ve kept the code, and I understand they must know the answer — we won’t send it to them.',
  securing: 'Locking…',
  lockGift: 'Lock the gift',

  unlockTitle: 'Welcome back',
  unlockBody: 'Open your gift with the answer you chose.',
  unlock: 'Open',
  unlocking: 'Opening…',
  wrongSecret: 'That’s not it. Try again.',
  tooMany: 'Too many tries. Wait 15 minutes, then try again.',
  forgot: 'Forgot it? Use your spare key',
  recoverTitle: 'Your spare key',
  recoverBody: 'Type the code you kept. You’ll then choose a new answer.',
  recoveryInput: 'Spare key',
  wrongRecovery: 'That code isn’t right.',
  useSecret: 'Use the answer instead',
  expiredTitle: 'Still there?',
  expiredBody: 'For safety we lock the page after a while. Your work is kept — open it again to carry on.',

  sectionsEyebrow: 'What’s inside',
  sectionsTitle: 'What will they find?',
  sectionsBody: 'The letter always comes first. Turn on what you’d like after it, and drag to set the order.',
  letterName: 'The letter',
  letterBody: 'An envelope with your words inside.',
  alwaysFirst: 'Always first',
  look: 'Have a look',
  dragHint: 'Drag to reorder',
  sectionInfo: {
    photo_wheel: { name: 'Photo wheel', body: 'Photos on a wheel they turn, one memory at a time.' },
    voice_note: { name: 'Voice note', body: 'Your voice, on a little record player.' },
    memory_calendar: { name: 'Memory calendar', body: 'Each photo on the day it happened.' },
    film_strip: { name: 'Film strip', body: 'Rolling film and a small cinema.' },
  } as Record<string, { name: string; body: string }>,
  noSections: 'Just the letter, for now. You can add more any time.',
  giftLanguageIs: 'The gift speaks',

  fillEyebrow: 'Filling it',
  fillTitle: 'Make it yours',
  readyCount: (ready: number, total: number) => `${ready} of ${total} ready`,
  letterTitle: 'Your letter',
  greeting: 'Greeting',
  greetingPlaceholder: 'My love,',
  message: 'Message',
  messagePlaceholder: 'Write what you want them to read…',
  signature: 'Signature',
  signaturePlaceholder: 'Yours, always',
  seeEnvelope: 'See it in its envelope',
  saving: 'Saving…',
  saved: 'Saved',
  saveError: 'Not saved — check your connection',
  addPhotos: 'Add photos',
  addMore: 'Add more',
  photosCount: (count: number) => `${count} ${count === 1 ? 'photo' : 'photos'}`,
  emptyWheel: 'Your photos will sit on this wheel.',
  emptyFilm: 'Your photos will roll by like film. Six or more fill both strips.',
  calendarTip: 'Tap a day to add its photos. Or add a batch — each lands on the day it was taken.',
  addByDate: 'Add photos by their date',
  dropHere: 'Drop your photos here',
  caption: 'A few words',
  captionPlaceholder: 'What was happening here?',
  memoryDate: 'Day',
  moveEarlier: 'Earlier',
  moveLater: 'Later',
  holdToMove: 'Tap a photo to edit it. Hold and drag to move it.',
  uploading: (left: number) => `Saving ${left} in the background`,
  failed: 'Didn’t upload',
  retryUpload: 'Try again',
  removed: 'Removed',
  undo: 'Undo',
  record: 'Record',
  stopRecording: 'Stop',
  chooseFile: 'Use a recording',
  recordingFor: (s: string) => `Recording · ${s}`,
  noteName: 'Name it',
  noteNamePlaceholder: 'Good morning',
  noteFallback: (n: number) => `Recording ${n}`,
  emptyVoice: 'Say something they can play again and again.',
  micIntro: 'Your browser will ask for the microphone. It’s only on while you record.',
  micDenied: 'The microphone is blocked. Allow it from the icon beside the address, or use a recording you already have.',
  micUnsupported: 'This browser can’t record. Use a recording you already have.',
  audioTooLong: 'Recordings can be up to 3 minutes.',
  audioTooBig: 'That file is too big (15 MB at most).',
  limitReached: 'That’s the most this section holds.',
  sectionHidden: 'Hidden until it has something in it.',

  previewTitle: 'Exactly as they’ll see it',
  editSection: 'Edit',
  publish: 'Send it to the necklace',
  publishing: 'Sending…',
  waitUploads: 'Finishing uploads…',
  needMessage: 'Write the letter first.',
  live: 'Live',

  publishedEyebrow: 'Done',
  publishedTitle: 'It’s on the necklace',
  publishedBody: 'When they bring the necklace to their phone, it asks for the lock, then it opens.',
  remember: 'They’ll be asked for',
  hintShown: 'with the hint',
  openGift: 'Open it as they will',
  keepEditing: 'Keep editing',
  changesLive: 'Anything you change from now shows up right away.',
  changeSecret: 'Change the lock',
  leaveWarning: 'Uploads are still running. Leave anyway?',
};

const ar: typeof en = {
  brand: 'ألفة',
  loading: 'لحظة…',
  invalidLink: 'هاد الرابط ما بيفتح أي هدية.',
  inactive: 'المتجر وقّف هاي الهدية.',
  networkError: 'ما في اتصال. تأكد من الإنترنت وجرّب كمان مرة.',
  retry: 'جرّب كمان مرة',
  back: 'رجوع',
  next: 'التالي',
  continue: 'كمّل',
  close: 'إغلاق',
  done: 'تمام',
  remove: 'احذف',
  uiLanguage: 'English',
  steps: ['القفل', 'شو جوّاها', 'التعبئة', 'نظرة أخيرة'],
  stepOf: (n: number, total: number) => `الخطوة ${n} من ${total}`,

  welcomeEyebrow: 'قبل ما توصله',
  welcomeTitle: 'هدية ما بيفتحها غيره',
  welcomeBody: 'اقفلها بإشي بتعرفوه إنتو الاثنين بس، وعبّيها بكلامك وصورك وصوتك، وشوفها بالضبط مثل ما رح يشوفها.',
  welcomePrivacy: 'كل إشي بيتقفل على موبايلك قبل ما يطلع منه. ما حدا بيقدر يفتحه، ولا حتى إحنا.',
  giftLanguage: 'لغة الهدية',
  start: 'يلا نبلّش',

  lockEyebrow: 'القفل',
  lockTitle: 'شو اللي بيفتحها؟',
  lockBody: 'رح ينسأل عنه أول ما يقرّب السنسال من موبايله. اختار إشي بيعرفه بدون ما يفكّر.',
  changeLockTitle: 'قفل جديد',
  types: { PIN: 'رقم', DATE: 'تاريخ', TEXT: 'سؤال' },
  typeHints: {
    PIN: '6 أرقام بتعرفوها إنتو الاثنين بس.',
    DATE: 'يوم تعارفكم، ذكرى سنوية…',
    TEXT: 'بيجاوب بكلماته.',
  },
  hint: 'تلميح صغير إله',
  optional: 'اختياري',
  hintPlaceholder: 'أول يوم التقينا',
  question: 'سؤالك',
  questionPlaceholder: 'وين كانت أول رحلة إلنا؟',
  answer: 'الجواب',
  answerAgain: 'كمان مرة، للتأكيد',
  pin: 'ستة أرقام',
  pinAgain: 'نفس الستة كمان مرة',
  date: 'التاريخ',
  mismatch: 'الاثنين مش متطابقين.',
  problems: {
    required: 'هاد لازم.',
    pinLength: 'لازم يكون ستة أرقام بالضبط.',
    pinWeak: 'سهل ينحزر — بلاش 123456 أو أرقام مكررة.',
    dateInvalid: 'هاد التاريخ مش موجود.',
    textShort: 'جواب أطول شوي لو سمحت.',
  },
  answerNote: 'الحروف الكبيرة والهمزات والتشكيل ما بتفرق.',
  lockScreenTitle: 'لعيونك فقط',
  theySee: 'هيك رح يشوفها',

  keepEyebrow: 'إشي واحد خبّيه',
  keepTitle: 'مفتاحك الاحتياطي',
  keepBody: 'إذا نسيت الجواب يوماً، هاد الكود هو الطريق الوحيد لترجع. ما منقدر نرجّعه إلك.',
  copy: 'انسخ',
  copied: 'انسخ ✓',
  download: 'احفظه كملف',
  screenshotTip: 'أو صوّر الشاشة، بتزبط.',
  keepConfirm: 'خبّيت الكود، وفاهم إنه لازم يعرف الجواب — ما رح نبعتله إياه.',
  securing: 'عم نقفلها…',
  lockGift: 'اقفل الهدية',

  unlockTitle: 'أهلين من جديد',
  unlockBody: 'افتح هديتك بالجواب اللي اخترته.',
  unlock: 'افتح',
  unlocking: 'عم نفتح…',
  wrongSecret: 'مش هاد. جرّب كمان مرة.',
  tooMany: 'محاولات كثير. استنّى 15 دقيقة وجرّب.',
  forgot: 'نسيته؟ استخدم المفتاح الاحتياطي',
  recoverTitle: 'المفتاح الاحتياطي',
  recoverBody: 'اكتب الكود اللي خبّيته، وبعدها بتختار جواب جديد.',
  recoveryInput: 'المفتاح الاحتياطي',
  wrongRecovery: 'هاد الكود مش صحيح.',
  useSecret: 'ارجع للجواب',
  expiredTitle: 'لسّاتك هون؟',
  expiredBody: 'للأمان منقفل الصفحة بعد فترة. شغلك محفوظ — افتحها وكمّل من مكانك.',

  sectionsEyebrow: 'شو جوّاها',
  sectionsTitle: 'شو رح يلاقي جوّا؟',
  sectionsBody: 'الرسالة دايماً أول إشي. شغّل اللي بدك ياه بعدها، واسحب لترتّب.',
  letterName: 'الرسالة',
  letterBody: 'ظرف وجوّاه كلامك.',
  alwaysFirst: 'دايماً أولاً',
  look: 'شوف',
  dragHint: 'اسحب لترتّب',
  sectionInfo: {
    photo_wheel: { name: 'دولاب الصور', body: 'صور على دولاب بيلفّه، ذكرى ذكرى.' },
    voice_note: { name: 'رسالة صوتية', body: 'صوتك على مشغّل أسطوانات صغير.' },
    memory_calendar: { name: 'تقويم الذكريات', body: 'كل صورة على اليوم اللي صارت فيه.' },
    film_strip: { name: 'شريط الفيلم', body: 'فيلم بيمشي وسينما صغيرة.' },
  },
  noSections: 'بس الرسالة هلأ. بتقدر تضيف كمان بأي وقت.',
  giftLanguageIs: 'لغة الهدية',

  fillEyebrow: 'التعبئة',
  fillTitle: 'خلّيها تشبهكم',
  readyCount: (ready: number, total: number) => `${ready} من ${total} جاهزين`,
  letterTitle: 'رسالتك',
  greeting: 'التحية',
  greetingPlaceholder: 'حبيبتي،',
  message: 'الرسالة',
  messagePlaceholder: 'اكتب اللي بدك ياه يقرأه…',
  signature: 'التوقيع',
  signaturePlaceholder: 'إلك دايماً',
  seeEnvelope: 'شوفها بظرفها',
  saving: 'عم نحفظ…',
  saved: 'محفوظة',
  saveError: 'ما انحفظت — تأكد من الإنترنت',
  addPhotos: 'ضيف صور',
  addMore: 'ضيف كمان',
  photosCount: (count: number) => (count === 1 ? 'صورة وحدة' : count === 2 ? 'صورتين' : `${count} صور`),
  emptyWheel: 'صورك رح تقعد على هاد الدولاب.',
  emptyFilm: 'صورك رح تمشي مثل الفيلم. ست صور أو أكثر بيعبّوا الشريطين.',
  calendarTip: 'اضغط على يوم لتضيف صوره. أو ضيف مجموعة وكل صورة بتروح على يوم تصويرها.',
  addByDate: 'ضيف صور حسب تاريخها',
  dropHere: 'افلت الصور هون',
  caption: 'كم كلمة',
  captionPlaceholder: 'شو كان صاير هون؟',
  memoryDate: 'اليوم',
  moveEarlier: 'لقدّام',
  moveLater: 'لورا',
  holdToMove: 'اضغط على صورة لتعدّلها. اضغط مطوّل واسحب لتنقلها.',
  uploading: (left: number) => `عم نحفظ ${left} بالخلفية`,
  failed: 'ما انرفعت',
  retryUpload: 'جرّب كمان',
  removed: 'انحذفت',
  undo: 'تراجع',
  record: 'سجّل',
  stopRecording: 'وقّف',
  chooseFile: 'استخدم تسجيل',
  recordingFor: (s: string) => `عم نسجّل · ${s}`,
  noteName: 'سمّيه',
  noteNamePlaceholder: 'صباح الخير',
  noteFallback: (n: number) => `تسجيل ${n}`,
  emptyVoice: 'قول إشي بيقدر يسمعه مرة ومرتين وعشرة.',
  micIntro: 'المتصفح رح يطلب المايك. بيشتغل بس وإنت عم تسجّل.',
  micDenied: 'المايك مسكّر. اسمح فيه من الأيقونة جنب الرابط، أو استخدم تسجيل عندك.',
  micUnsupported: 'هاد المتصفح ما بيسجّل. استخدم تسجيل عندك.',
  audioTooLong: 'التسجيل لحد 3 دقايق.',
  audioTooBig: 'الملف كبير (15 ميغا بالكثير).',
  limitReached: 'هاد أكثر إشي بيساعه هاد القسم.',
  sectionHidden: 'مخفي لحد ما يصير فيه إشي.',

  previewTitle: 'بالضبط مثل ما رح يشوفها',
  editSection: 'عدّل',
  publish: 'ابعتها عالسنسال',
  publishing: 'عم نبعت…',
  waitUploads: 'عم نكمّل الرفع…',
  needMessage: 'اكتب الرسالة أول.',
  live: 'شغّالة',

  publishedEyebrow: 'خلصنا',
  publishedTitle: 'صارت عالسنسال',
  publishedBody: 'لما يقرّب السنسال من موبايله، بتسأله عن القفل، وبعدين بتفتح.',
  remember: 'رح ينسأل عن',
  hintShown: 'مع التلميح',
  openGift: 'افتحها مثله',
  keepEditing: 'كمّل تعديل',
  changesLive: 'أي إشي بتغيّره من هلأ بيظهر فوراً.',
  changeSecret: 'غيّر القفل',
  leaveWarning: 'في رفع لسا شغّال. بدك تطلع؟',
};

export const setupCopy = { en, ar };
export type SetupCopy = typeof en;
